/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiPublicChecklistDownloadRouteImport } from './routes/api/public/checklist-download'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChecklistDownloadRoute =
  ApiPublicChecklistDownloadRouteImport.update({
    id: '/api/public/checklist-download',
    path: '/api/public/checklist-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/checklist-download': typeof ApiPublicChecklistDownloadRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/checklist-download': typeof ApiPublicChecklistDownloadRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/checklist-download': typeof ApiPublicChecklistDownloadRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/checklist-download'
    | '/lovable/email/events'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/checklist-download'
    | '/lovable/email/events'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/checklist-download'
    | '/lovable/email/events'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicChecklistDownloadRoute: typeof ApiPublicChecklistDownloadRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checklist-download': {
      id: '/api/public/checklist-download'
      path: '/api/public/checklist-download'
      fullPath: '/api/public/checklist-download'
      preLoaderRoute: typeof ApiPublicChecklistDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicChecklistDownloadRoute: ApiPublicChecklistDownloadRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
